/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        manutencao = new javax.swing.JMenu();
        marca = new javax.swing.JMenuItem();
        modelo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cliente = new javax.swing.JMenuItem();
        carro = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        locacao = new javax.swing.JMenuItem();
        ajuda = new javax.swing.JMenu();
        sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Cadastros");
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-carro.png"))); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(1200, 60));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(1200, 60));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(1200, 60));

        manutencao.setText("Manutenção");
        manutencao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        manutencao.setMaximumSize(new java.awt.Dimension(120, 25));
        manutencao.setMinimumSize(new java.awt.Dimension(120, 25));
        manutencao.setPreferredSize(new java.awt.Dimension(120, 25));

        marca.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        marca.setText("Marca");
        marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaActionPerformed(evt);
            }
        });
        manutencao.add(marca);

        modelo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        modelo.setText("Modelo");
        modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloActionPerformed(evt);
            }
        });
        manutencao.add(modelo);
        manutencao.add(jSeparator1);

        cliente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cliente.setText("Cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        manutencao.add(cliente);

        carro.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        carro.setText("Carro");
        carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carroActionPerformed(evt);
            }
        });
        manutencao.add(carro);

        jMenuBar1.add(manutencao);

        jMenu1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu1.setLabel("Lançamentos    ");

        locacao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        locacao.setText("Locação");
        locacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locacaoActionPerformed(evt);
            }
        });
        jMenu1.add(locacao);

        jMenuBar1.add(jMenu1);

        ajuda.setText("Ajuda    ");
        ajuda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        sobre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sobre.setText("Sobre");
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });
        ajuda.add(sobre);

        jMenuBar1.add(ajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 603, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
        FormMarca autor = new FormMarca(this, true);
        autor.setTitle("Cadastro de Autores");
        autor.setLocationRelativeTo(null);
        autor.setVisible(true);
    }//GEN-LAST:event_marcaActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        FormCliente cliente = new FormCliente(this, true);
        cliente.setTitle("Cadastro de Clientes");
        cliente.setLocationRelativeTo(null);
        cliente.setVisible(true);
    }//GEN-LAST:event_clienteActionPerformed

    private void carroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carroActionPerformed
        FormCarro filme = new FormCarro(this, true);
        filme.setTitle("Cadastro de Filmes");
        filme.setLocationRelativeTo(null);
        filme.setVisible(true);
    }//GEN-LAST:event_carroActionPerformed

    private void modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloActionPerformed
        FormModelo produtora = new FormModelo(this, true);
        produtora.setTitle("Cadastro de Produtoras");
        produtora.setLocationRelativeTo(null);
        produtora.setVisible(true);
    }//GEN-LAST:event_modeloActionPerformed

    private void locacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locacaoActionPerformed
        FormLocacao pacote = new FormLocacao(this, true);
        pacote.setTitle("Cadastro de Pacotes");
        pacote.setLocationRelativeTo(null);
        pacote.setVisible(true);
    }//GEN-LAST:event_locacaoActionPerformed

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed
        JOptionPane.showMessageDialog(null,"\nSistema de Cadastros\n\n" + "Para entrar em contato com o suporte ligue para 0800-808080");
    }//GEN-LAST:event_sobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajuda;
    private javax.swing.JMenuItem carro;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem locacao;
    private javax.swing.JMenu manutencao;
    private javax.swing.JMenuItem marca;
    private javax.swing.JMenuItem modelo;
    private javax.swing.JMenuItem sobre;
    // End of variables declaration//GEN-END:variables
}
